# Training configuration
GPU: [0]

VERBOSE: False

MODEL:
  MODE: 'LIEDNet_LOLv1'

# Optimization arguments.
OPTIM:
  BATCH: 8
  EPOCHS: 4000
  # EPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 128
  TRAIN_DIR: '/data/lowlight_data/LOLv1/Train'       # path to training data
  VAL_DIR: '/data/lowlight_data/LOLv1/Test' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
